#!/bin/bash

##
## Usage: my-fortune [-h|--help|lang] [fortune parameteres]
## 
##    Options:
##      -h, --help        : Display this message.
##      lang              : language of the fortune message, random by default
##      fortune parameters: see man fortune
## 

language=""
languages=( "hu" "de" "en" )
dir="/usr/share/games/fortune"
script=`basename $0`

function usage()
{
echo -e "Usage: $script [-h|--help|lang] [fortune parameteres]

   Options:
     -h, --help        : Display this message.
     lang              : language of the fortune message, random by default
     fortune parameters: see man fortune
"  
}

function rndlang()
{
  let "randnum=$RANDOM % ${#languages[*]} "
  language=${languages[randnum]}
}

if [ -z $1 ]
then
	rndlang
else
  case $1 in
  "-h"|"--help") usage; exit;;
  *) for lan in ${languages[@]}
	  do
	  if [ "$lan" == "$1" ]; then
	    language=$1
      shift
	    break
	  fi
	  done
	  if [ -z $language ]; then
		  rndlang
    fi;;
  esac
fi

case "$language" in
de) dir="$dir/de";;
hu) dir="$dir/hu";;
en) dir="$dir";;
*) echo "$script: hiba: \"$language\" nyelven nincs bejegyzés! Paraméterként továbbadjuk fortune-nak!" >2;;
esac

case "$language" in
#de) fortune "$@" "$dir" | iconv -f=iso-8859-2 -t=utf-8;;
*) fortune "$@" "$dir";;
esac


